apiVersion: apps/v1
kind: Deployment
metadata:
  name: surbhi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surbhi
  template:
    metadata:
      labels:
        app: surbhi
    spec:
      containers:
      - name: surbhigulati002
        image: surbhigulati002/sit323-737-2024-t1-prac7p:1.1.1
        ports:
        - containerPort: 3000